# Configuration de l'application Chantier Accès
# Ce fichier est chargé au démarrage par AppConfig

# Informations du chantier
chantier.nom=Chantier Principal ENSPY
chantier.adresse=Rue de l'Université, Yaoundé, Cameroun

# Paramètres de l'application
app.version=1.0
app.timeout.session=15
app.badge.alerte.jours=7
